name: flutter_core
description: "Core Flutter Project."
version: 0.0.1
homepage: https://gitlab.zvalley.io/flutter/flutter_ume_action_kit_ui
publish_to: none

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # zvalley_ui:
  #   git:
  #     url: https://gitlab.zvalley.io/flutter/ui.git
  #     ref: release-v1.0.0

  get:
  get_storage:
  cached_network_image:
  dio:
  dio_cache_interceptor:
  permission_handler:
  connectivity_plus:
  device_info_plus:
  package_info_plus:
  pull_to_refresh:
  url_launcher:
  app_settings:

  # Flutter Ume
  flutter_ume:
    git:
      url: https://github.com/YoukanoOfficial/flutter-ume.git
      ref: v1.0.0
  flutter_ume_action:
    git:
      url: https://github.com/YoukanoOfficial/flutter-ume
      ref: v2.0.0

# dependency_overrides:
#   vm_service: ^14.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
